-- ── Tables ────────────────────────────────────────────────────────────────────

-- Needed for gen_random_uuid() if not already enabled in the project.
create extension if not exists pgcrypto;

create table public.jobs (
  id                uuid         primary key default gen_random_uuid(),
  user_id           uuid         not null references auth.users(id) on delete cascade,
  status            text         not null default 'created'
                                 check (status in ('created','uploaded','queued','running','done','error')),
  video_object_path text,
  result_prefix     text,
  config            jsonb        not null default '{}'::jsonb,
  error             text,
  created_at        timestamptz  not null default now(),
  updated_at        timestamptz  not null default now()
);

create table public.artifacts (
  id           uuid         primary key default gen_random_uuid(),
  job_id       uuid         not null references public.jobs(id) on delete cascade,
  kind         text         not null,
  object_path  text         not null,
  meta         jsonb        not null default '{}'::jsonb,
  created_at   timestamptz  not null default now()
);

-- ── updated_at trigger ────────────────────────────────────────────────────────

create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger jobs_updated_at
  before update on public.jobs
  for each row execute procedure public.set_updated_at();

-- ── Indexes ───────────────────────────────────────────────────────────────────

create index jobs_user_id_idx      on public.jobs(user_id);
create index jobs_status_idx       on public.jobs(status);
create index artifacts_job_id_idx  on public.artifacts(job_id);

-- ── Row Level Security ────────────────────────────────────────────────────────
-- Reads via authenticated Supabase client (anon key + session).
-- All writes happen via server routes / worker using the service role key,
-- so no INSERT/UPDATE/DELETE policies are needed here.

alter table public.jobs      enable row level security;
alter table public.artifacts enable row level security;

create policy "users_select_own_jobs"
  on public.jobs for select
  using (auth.uid() = user_id);

create policy "users_select_own_artifacts"
  on public.artifacts for select
  using (
    exists (
      select 1 from public.jobs
      where id = artifacts.job_id
        and user_id = auth.uid()
    )
  );

-- ── Storage buckets (run these in the Supabase dashboard or via CLI) ──────────
-- create bucket videos    (private, max 200 MB per file)
-- create bucket artifacts (private)
--
-- No Storage policies needed because all uploads/downloads go through
-- signed URLs generated by the service-role key on the server.
